" primary interest/use:

set number    " Add numbers to each line on left side

filetype on         " Enable file type detection; try to detect type of file in use
filetype indent on  " Load an indent file for detected file type
filetype plugin on  " Enable plugins and load plugin for the detected file type

syntax on                     " syntax highlighting
let python_highlight_all = 1  " enable all Python syntax highlighting features

set autoindent      " indent when moving to the next line while writing code
set shiftwidth=4    " shift width to 4 spaces
set tabstop=4       " tab width 4 spaces
set expandtab       " tab key expands to space characters

set backspace=indent,eol,start  " generally reasonable use of backspace key

set incsearch   " incremental search, <CR> to stop
set showmatch   " show matching words during a search
set ignorecase  " ignore capital letters during search
set smartcase   " case-insensitive unless providing capital letters; overrides ignorecase option if searching for capital letters.
set hlsearch    " use highlighting when doing a search

set ruler      " current line number at bottom-right
set wildmenu   " command-line completion, use <tab> to move around, <CR> to validate

" primarily reminders:

set showcmd       " show partial command you type in the last line of the screen
set history=1000  " Set the commands to save in history; default is 20

set nocompatible    " Disable compatibility with vi which can cause unexpected issues

set wildmenu  " Enable auto completion menu after pressing TAB
set wildmode=list:longest " Make wildmenu behave like bash completion

" set cursorline    " Highlight cursor line underneath the cursor horizontally
" set cursorcolumn  " Hightlight cursor line underneath the cursor vertically

" Do not wrap lines. allow long lines to extend as far as the line goes.
" set nowrap

" Ignore these file extensions
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" Do not save backup files
" set nobackup

" Do not let cursor scroll below or above N number of lines when scrolling
" set scrolloff=10

" set hidden  " " 'possibility to have more than one unsaved buffers'

" YAML config
" let g:indentLine_char = '|' " this is dependent upon a plugin which I don't have
